# Generated by Django 5.2.5 on 2025-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
